### ISSUE TITLE
Move from float to integer (0-100)

### ISSUE THREAD

**Issue by robsonfelix** [wrodie/ha_behringer_mixer#35]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/wrodie/ha_behringer_mixer/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When using the faders with other HA components, they won't work properly. Using the slider-button-card for example will correctly display values already in place but users won't be able to change volumes for example without being either 0 or 1. It looks to me this is due to numbers being float between 0 and 1.

### Describe the solution you'd like

I would rather have the numbers as integers from 0-100.

### Describe alternatives you've considered

I don't have any alternatives. I need to use this integration but the look and feel using any UI controls already in place won't work.

### Additional context

I am putting together a mixer UI I can use at my house through my companion Home Assistant App, therefore the mixer has to work in horizontal mode and not vertical mode, therefore the use of sliders is paramount to success.

**Comment by wrodie** [comment]
I don't really want to do move to ints for a variety of reasons:
 - moving away from floats to a 0-100 range would reduce granularity for the mixer
 - other HA widgets support the float - eg the standard slider
 - The standard HA media player uses floats (0-1) for volume levels - https://developers.home-assistant.io/docs/core/entity/media-player/

I think this is an issue with the Slider-button card not handling the different maximum of (1 rather than 100). 
I've looked at the code quickly  and it looks like in
https://github.com/mattieha/slider-button-card/blob/main/src/slider-button-card.ts: 406 the updateValue function is called and is passing in a percentage, rather than the correct value.
Which is why it displays properly until you attempt to do something with it.
There are a few issues logged by people in the slider button card github asking for support for generic values/floats etc.  So I don't think this is an issue with the mixer-card specifically.

**Comment by wrodie** [comment]
As mentioned by @robsonfelix - in #38 , I could potentially look at having an option that gives the user the option to have 0-100 or 0-1 as ranges. 
The conversion assumption would just be to multiple/divide by 100

**Comment by wrodie** [comment]
I've just release v0.1.9 which has a new configuration option on setup that sets the scale from 1-100 instead of 0-1.  It is off by default.
I've tested it with the slider-button card and it seems to work quite well.

**Comment by robsonfelix** [comment]
![image](https://github.com/wrodie/ha_behringer_mixer/assets/9100568/0f8a9b53-e6ec-481e-8b16-904afc9adb18)

I do not see the option after upgrading. I already rebooted many times.

**Comment by robsonfelix** [comment]
U da man! thank you!
